# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTaxiCodingTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTaxiCodingTest
    pod 'Moya/RxSwift'
    pod 'RxCocoa'
    pod 'RxSwift'
    pod 'RxDataSources'

  target 'MyTaxiCodingTestTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest'
  end

end
